### ISSUE TITLE
Package grooming and performance improvements

### ISSUE THREAD

**Issue by dieghernan** [rOpenGov/eurostat#230]
Hi @antagomir @pitkant:

Now that the package moved to a new version, let me share with you some potential improvements I would like to suggest:

# Documentation

- Currently the documentation is still using the old syntax `\code{}, \link{}`, etc. I would like to propose moving to markdown  (see https://roxygen2.r-lib.org/articles/rd-formatting.html#turning-on-markdown-support-1). It is also quite easy to convert the current docs to markdown with {roxygen2md} package.
- Also, the code styling can me improved using the `styler` package, adopted by the Tidyverse.
- The DESCRIPTION file can also be normalized with the `usethis` package.
- The `@family` tag (https://roxygen2.r-lib.org/articles/rd.html#cross-references) is quite useful for cross-referencing families of functions. It also can be used for presenting a more clear index on the pkgdown page. Forexample, [{giscoR}](https://ropengov.github.io/giscoR/reference/index.html) is structured on categories:

```yaml
reference:
- title: Political
  desc: These functions return `sf` objects with political boundaries
  contents: has_concept("political")
- title: Infrastructures
  desc: These functions return `sf` objects with man-made features
  contents: has_concept("infrastructure")
...
```
- Accordingly, the reference page could be reestructured to facilitate the navigation of users.

# Dependencies and tests

This is a sensitive issue. Currently the package has 19 Imports and 13 Suggests. Also, the package has more than 100 tests for `get_eurostat_geospatial()` and still the coverage is below 55%.

These two issues cause that the package is heavy when installing on a fresh system and also really slow to tests.

I think it is possible to reduce dependencies to 17+5 (get rid of 10 packages) with almost no costs. On the test side, more work is needed, but probably there are room for improvement.

As a suggestion, {giscoR} could help with the spatial part but {sf} would be still needed.

I see the **Documentation** part quite easy (I can even set an action for performing these tasks). Also  I can work on reducing dependencies.

Let mw know your thoughs, regards
